#' Launch the first shinyapp for to look into what variables are available in the abstract.
#'
#'
#' @description This function launches a Shiny app that displays each abstract alongside the data elements you want to extract. The app provides an interactive interface for manually entering this information, helping to fill out the _manual column generated by the `add_predefined_vars()` function in the training set.
#'
#' @return Shiny app.
#'
#' @export
glance_manual_app <- function() {
  app_dir <- system.file("shiny-app1/app.R", package = "metaextractoR")

  shiny::runApp(app_dir, display.mode = "normal")
}
