# Shinyapp: manual validation

#' @title manual_validation_app
#'
#' @description This Shiny app allows you to manually review the results generated by the `process_with_ollama()` function. By uploading a testing dataset with LLM-extracted values, you can systematically check and validate each field filled out by the model.
#'
#' @examples
#'
#' if (interactive()) {
#'   manual_validation_app()
#' }
#' @return Runs a shiny app.
#'
#' @export
manual_validation_app <- function() {
  app_dir <- system.file("shiny-app/app.R", package = "metaextractoR")

  shiny::runApp(app_dir, display.mode = "normal")
}
